version: '3.8'
services:
  DB:
    image: postgres:15
    environment:
      - POSTGRES_DB=interview_prep
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
  
  app:
    build: .
    ports: 
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=interview_prep
    depends_on:
      - DB

volumes:
  postgres_data:

      
